
# Subscriber
project_id: "playground-287918"
subscription_id: "lookup-in-queue"

# If we dont get a message for two minutes, resubscribe
listen_timeout: 300

# Credentials
credential_path: "./playground-287918-35ce241b55df.json"

